### ISSUE TITLE
Replay attack for signed messages

### ISSUE THREAD

**Issue by YamenMerhi** [lukso-network/lsp-smart-contracts#151]
## What is this issue about?
The [LSP6-KeyManager](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md) uses a signed message for executing a relay call through `executeRelayCall(...)` function.
According to the LSP6 Specs:
> The message to sign MUST be of the following format: **`KeyManager address`** + **`signer nonce`** + **`data payload`** . These 3 parameters MUST be:
> - packed encoded (not zero padded, leading 0s are removed)
> - hashed with keccak256
> 
> The final message MUST be signed using ethereum specific signature, based on [EIP-191](https://eips.ethereum.org/EIPS/eip-191).

This way of signing messages, introduces a security risk, allowing users to replay these messages across different chains if:
- The **KeyManager** is deployed on the same address    ||  (Could be done  ✅ )
- The **nonce** of the signer is the same                             ||  (Could be done ✅ )
- The **data (Payload)** is the same                                     ||  (Could be done ✅ )

## Suggested Solutions
Looking at the **[EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)**, they included the **`chainId`** in the transaction to ensure that a transaction could be signed for only one chain. 
Message signing utilizes the same mechanisms as transaction signing, but message signing doesn't include this kind of extra information. It only includes what you give it to, so in our case, it will include just the **KeyManager address**, the **nonce**, and the **data (Payload)**.
We could have 2 solutions: 
- Drop [EIP-191](https://eips.ethereum.org/EIPS/eip-191) support for signing messages and adopt [EIP-712](https://eips.ethereum.org/EIPS/eip-712) which includes the chainId in the signing message, and is also used to structure the signed message so it is more readable.
- Including the chainId in the signed message without using the [EIP-712](https://eips.ethereum.org/EIPS/eip-712).

## To watch out for:
- `chainId` should be used and not `networkId`, as some chains have the same networkId but different chainId.
 **ETH** and **ETC** have the same networkId but different chainId.
- **chainId** shouldn't be referenced with a variable in the constructor while deploying: ❌ ❌ ❌ ❌ 

```solidity
    constructor(address _target) {
        target = _target;
        chainId = block.chainid;
    }
```
Instead it should be mentioned **explicitly** in the smart contract while forming the signed message:  ✅ ✅ ✅ ✅
```solidity
        bytes memory signedMessage = abi.encodePacked(
            block.chainid,
            address(this), // needs to be signed for this keyManager
            _nonce,
            _data
        );
```

Because, in the event of a **post-deployment hard fork** of the chain, the chainId cannot be updated, and signatures may be replayed across both versions of the chain. As a result, an attacker could reuse signatures to execute the relay call twice.

**Comment by frozeman** [comment]
We decide against this as it increases the complexity on the signing side a lot, especially for non web libraries like web3swift and others. While the only benefit is the increased visibility in tools like MetaMask, which are not the preferred ways to handle, manage and use a Universal profile.

In the current method we will also sign `chain id`, which will make the signature safe from replay attacks.

getting the call data from a call to the `executeRelayCall(signature, none, data)` function, is as simple as cutting of the first bytes. So visibility and decodability is given for the current way of signing, while making signing as simple, as hashing and signing a simple message `sign(keccak256(chainid, keyManagerAddress, nonce, data))`
