### ISSUE TITLE
LSP8 setApproveForAll

### ISSUE THREAD

**Issue by DanielAbalde** [lukso-network/lsp-smart-contracts#225]
Currently LSP8 only allows approval of operators **per token** using:

```solidity
function authorizeOperator(address operator, bytes32 tokenId) public
```
https://docs.lukso.tech/standards/smart-contracts/lsp8-identifiable-digital-asset/#authorizeoperator

However, an option to **approve an operator for all tokens** is missing. A "setApproveForAll" equivalent should be taken into consideration.

In fact, [ILSP8CompatibleERC721](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/contracts/LSP8IdentifiableDigitalAsset/extensions/ILSP8CompatibleERC721.sol) lacks the "setApprovalForAll" method that is present in the EIP721 (and EIP1155 too).
https://eips.ethereum.org/EIPS/eip-721
https://eips.ethereum.org/EIPS/eip-1155

Working on an NFT exchanger, where two people can exchange multiple NFTs using the contract as the intermediary, I wanted to support LSP8 but found this limitation. The UX of this contract is quite bad, the user has to approve the Swapper contract as an operator on every NFT contract they wants to trade, then register a swap and get its id, then both parties must deposit their NFTs into the Swapper contract and then one of the two can claim the other's NFTs. That's quite a few signatures needed for a fairly simple process, so the user experience (while maintaining the properties offered by this implementation) is quite tedious. So is even worse when the user does not have to approve the Swapper contract on each NFT contract as an operator, but has to do it for each token (even if these are put together in the same transaction, on the next swap they will have to repeat the approval for other (probably new) tokens ids). So a "setApprovalForAll" is quite convenient, in addition to complete compatibility with ERC721, as it means that the user only has to approve on the NFT contract once.

The [OpenZeppelin implementation of ERC721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol) includes two mappings for approvals:
```solidity
  // Mapping from token ID to approved address
    mapping(uint256 => address) private _tokenApprovals;

    // Mapping from owner to operator approvals
    mapping(address => mapping(address => bool)) private _operatorApprovals;
  ```
However [LSP8](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol) just include one:
```solidity

    // Mapping a `tokenId` to its authorized operator addresses.
    mapping(bytes32 => EnumerableSet.AddressSet) internal _operators;
```

So to expose an equivalent to "setApprovalForAll" seems to me to be too little cost for the positive impact of Lukso's NFTs being more compatible with the NFT platforms in the Ethereum ecosystem.

**Comment by CJ42** [comment]
@DanielAbalde we have created a PR to add `setApprovalForAllI(...)` and the `_operatorsApprovals` mapping in the backward compatible version of LSP8 `LSP8CompatibleERC721`.

This will at least be a better improvement, so you might want to use `LSP8CompatibleERC721` for your use case of NFT Swapper.

Regarding adding the `setApprovalForAll(...)` function in LSP8 directly, this should have to be discussed further, as if introduced, it will be a new feature but also breaking change (LSP8 interface id will change).

@frozeman @YamenMerhi @skimaharvey

**Comment by DanielAbalde** [comment]
Great @CJ42, thanks for include it on `LSP8CompatibleERC721`!

So on `LSP8`, how can a key be approved by a owner to operate with all its tokens? Can it be done through the Key Manager or other controller? If this is the case then, even if it makes it more difficult for developers, I guess it's ok not to include it in `LSP8`. Ethereum's NFT approval system makes a bad UX, so perhaps compatibility there is not the priority.
