### ISSUE TITLE
Documentation Mismatch

### ISSUE THREAD

**Issue by MichaelStandenASM** [lukso-network/lsp-smart-contracts#414]
I'm trying to run this configure allowed addresses as per the documentation here: https://docs.lukso.tech/standards/universal-profile/lsp6-key-manager/#allowed-addresses

From what I can see in the repository, this key is not implemented. The test suite uses `AddressPermissions:AllowedCalls` instead. https://github.com/lukso-network/lsp-smart-contracts/blob/0566ea1be44c30b9c37e9beb72a3c29c2caf2087/tests/LSP6KeyManager/tests/AllowedAddresses.test.ts#L80

Can someone please confirm if I am misreading this or the documentation is inconsistent?

**Comment by YamenMerhi** [comment]
Hey @MichaelStandenASM, If you look at the `main` branch or the latest release, the code matches the documentation. What you are looking at is the `develop` branch, these are the changes we plan to introduce in our next release and change the documentation to match the new behavior.

**Comment by MichaelStandenASM** [comment]
Ah thanks! Is there a timeline for this release @YamenMerhi? We have some tight deadlines and I'd prefer to take the latest codebase, assuming it's stable.

**Comment by YamenMerhi** [comment]
@MichaelStandenASM I see, currently, we are in an audit process, so things might take a while and the release might not be available very soon.

**Comment by CJ42** [comment]
Closing as already implemented
