### ISSUE TITLE
LSP-6 virtual functions

### ISSUE THREAD

**Issue by MichaelStandenASM** [lukso-network/lsp-smart-contracts#440]
Hey team. We're working on extending your contracts and need to override some functions for our use cases. Would you be open to including the `virtual` keyword on internal functions in the `Core` contracts?

Specifically, I want to override `contracts/LSP6KeyManager/LSP6KeyManagerCore.sol:_verifyPermissions` but see value in applying this across all your components. 

Happy to submit a PR

**Comment by YamenMerhi** [comment]
Hey @MichaelStandenASM , thanks for pointing this out!
Feel free to open the PR :)

**Comment by CJ42** [comment]
Hey @MichaelStandenASM 
Thanks for opening an issue.
Yes agree that would be good to give the ability to override the functions of LSP6.
Feel free to open a PR with these changes :)

**Comment by MichaelStandenASM** [comment]
Merged. Closing this ticket
