### ISSUE TITLE
[Bug]: Smart contract extending LSP7DigitalAsset is not recognized as a ERC725Y interface in 0.10.3

### ISSUE THREAD

**Issue by visse509** [lukso-network/lsp-smart-contracts#655]
### Describe the issue:

I recently upgraded from 0.9.0 to 0.10.3 and my custom smart contract that is extending the LSP7DigitalAsset smart contract is no longer recognized as an ERC725Y contract. 

Tested using this tool: https://erc725-inspect.lukso.tech/getData

### Environment

Compiler version: 0.8.8

### Code example to reproduce the issue:

`contract TestContract is LSP7DigitalAsset {
...
}`

**Comment by CJ42** [comment]
@visse509 the issue probably comes from the erc725-inspect website, which does not recognise the new ERC165 interface IDs of ERC725Y.

- The version `0.9.0` of the lsp-smart-contracts --> uses `4.2.0` version of `@erc725/smart-contracts`: https://github.com/lukso-network/lsp-smart-contracts/blob/e1657de39dae3e31e764ef24ea3f5bd071e092f1/package.json#L88C34-L88C39
- The version `0.10.3` of the lsp-smart-contracts --> uses `5.1.0` version of `@erc725/smart-contracts`: https://github.com/lukso-network/lsp-smart-contracts/blob/8f0cfb2c573c44702d3155375b2d935b043416b3/package.json#L101

There was a breaking change in v5.0.0 of `@erc725/smart-contracts`, where we removed function overloading, which changed the interface ID of ERC725X and Y: https://github.com/ERC725Alliance/ERC725/releases/tag/v5.0.0

I suggest to re-open this issue in the erc725-inspect Github repository: https://github.com/lukso-network/tools-erc725-inspect/issues

**Comment by CJ42** [comment]
Closing as not related to this repository
